<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-06-02">

<title>Day 8: Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Day8_LogisticRegression_files/libs/clipboard/clipboard.min.js"></script>
<script src="Day8_LogisticRegression_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Day8_LogisticRegression_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Day8_LogisticRegression_files/libs/quarto-html/popper.min.js"></script>
<script src="Day8_LogisticRegression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Day8_LogisticRegression_files/libs/quarto-html/anchor.min.js"></script>
<link href="Day8_LogisticRegression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Day8_LogisticRegression_files/libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Day8_LogisticRegression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Day8_LogisticRegression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Day8_LogisticRegression_files/libs/bootstrap/bootstrap-dfb3f4843b9b0ce307f095fcbeec1e0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">1</span> Overview</a></li>
  <li><a href="#why-not-linear-regression" id="toc-why-not-linear-regression" class="nav-link" data-scroll-target="#why-not-linear-regression"><span class="header-section-number">2</span> Why Not Linear Regression?</a>
  <ul class="collapse">
  <li><a href="#the-logit-transformation" id="toc-the-logit-transformation" class="nav-link" data-scroll-target="#the-logit-transformation"><span class="header-section-number">2.1</span> The Logit Transformation</a></li>
  </ul></li>
  <li><a href="#example-1-simple-logistic-regression-chd-on-sysbp" id="toc-example-1-simple-logistic-regression-chd-on-sysbp" class="nav-link" data-scroll-target="#example-1-simple-logistic-regression-chd-on-sysbp"><span class="header-section-number">3</span> Example 1: Simple Logistic Regression (CHD on sysBP)</a>
  <ul class="collapse">
  <li><a href="#the-question" id="toc-the-question" class="nav-link" data-scroll-target="#the-question"><span class="header-section-number">3.1</span> The Question</a></li>
  <li><a href="#checking-variable-form" id="toc-checking-variable-form" class="nav-link" data-scroll-target="#checking-variable-form"><span class="header-section-number">3.2</span> Checking Variable Form</a></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model"><span class="header-section-number">3.3</span> Fitting the Model</a></li>
  <li><a href="#odds-ratios-and-confidence-intervals" id="toc-odds-ratios-and-confidence-intervals" class="nav-link" data-scroll-target="#odds-ratios-and-confidence-intervals"><span class="header-section-number">3.4</span> Odds Ratios and Confidence Intervals</a></li>
  <li><a href="#predicted-probabilities" id="toc-predicted-probabilities" class="nav-link" data-scroll-target="#predicted-probabilities"><span class="header-section-number">3.5</span> Predicted Probabilities</a></li>
  <li><a href="#visualizing-the-fitted-curve" id="toc-visualizing-the-fitted-curve" class="nav-link" data-scroll-target="#visualizing-the-fitted-curve"><span class="header-section-number">3.6</span> Visualizing the Fitted Curve</a></li>
  <li><a href="#a-note-on-categorizing-continuous-predictors" id="toc-a-note-on-categorizing-continuous-predictors" class="nav-link" data-scroll-target="#a-note-on-categorizing-continuous-predictors"><span class="header-section-number">3.7</span> A Note on Categorizing Continuous Predictors</a></li>
  </ul></li>
  <li><a href="#example-2-multiple-logistic-regression" id="toc-example-2-multiple-logistic-regression" class="nav-link" data-scroll-target="#example-2-multiple-logistic-regression"><span class="header-section-number">4</span> Example 2: Multiple Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#the-question-1" id="toc-the-question-1" class="nav-link" data-scroll-target="#the-question-1"><span class="header-section-number">4.1</span> The Question</a></li>
  <li><a href="#checking-variable-form-for-each-predictor" id="toc-checking-variable-form-for-each-predictor" class="nav-link" data-scroll-target="#checking-variable-form-for-each-predictor"><span class="header-section-number">4.2</span> Checking Variable Form for Each Predictor</a></li>
  <li><a href="#fitting-the-full-model" id="toc-fitting-the-full-model" class="nav-link" data-scroll-target="#fitting-the-full-model"><span class="header-section-number">4.3</span> Fitting the Full Model</a></li>
  <li><a href="#adjusted-odds-ratios" id="toc-adjusted-odds-ratios" class="nav-link" data-scroll-target="#adjusted-odds-ratios"><span class="header-section-number">4.4</span> Adjusted Odds Ratios</a></li>
  <li><a href="#comparing-nested-models-likelihood-ratio-test" id="toc-comparing-nested-models-likelihood-ratio-test" class="nav-link" data-scroll-target="#comparing-nested-models-likelihood-ratio-test"><span class="header-section-number">4.5</span> Comparing Nested Models: Likelihood Ratio Test</a></li>
  <li><a href="#model-selection-with-aic" id="toc-model-selection-with-aic" class="nav-link" data-scroll-target="#model-selection-with-aic"><span class="header-section-number">4.6</span> Model Selection with AIC</a></li>
  <li><a href="#final-model-and-its-odds-ratios" id="toc-final-model-and-its-odds-ratios" class="nav-link" data-scroll-target="#final-model-and-its-odds-ratios"><span class="header-section-number">4.7</span> Final Model and Its Odds Ratios</a></li>
  </ul></li>
  <li><a href="#example-3-classification-and-predictive-performance" id="toc-example-3-classification-and-predictive-performance" class="nav-link" data-scroll-target="#example-3-classification-and-predictive-performance"><span class="header-section-number">5</span> Example 3: Classification and Predictive Performance</a>
  <ul class="collapse">
  <li><a href="#generating-predicted-probabilities" id="toc-generating-predicted-probabilities" class="nav-link" data-scroll-target="#generating-predicted-probabilities"><span class="header-section-number">5.1</span> Generating Predicted Probabilities</a></li>
  <li><a href="#confusion-matrix-at-threshold-0.5" id="toc-confusion-matrix-at-threshold-0.5" class="nav-link" data-scroll-target="#confusion-matrix-at-threshold-0.5"><span class="header-section-number">5.2</span> Confusion Matrix at Threshold = 0.5</a></li>
  <li><a href="#confusion-matrix-at-threshold-0.15-the-event-rate" id="toc-confusion-matrix-at-threshold-0.15-the-event-rate" class="nav-link" data-scroll-target="#confusion-matrix-at-threshold-0.15-the-event-rate"><span class="header-section-number">5.3</span> Confusion Matrix at Threshold = 0.15 (the Event Rate)</a></li>
  <li><a href="#sensitivity-specificity-ppv-npv" id="toc-sensitivity-specificity-ppv-npv" class="nav-link" data-scroll-target="#sensitivity-specificity-ppv-npv"><span class="header-section-number">5.4</span> Sensitivity, Specificity, PPV, NPV</a></li>
  <li><a href="#roc-curve-and-auc" id="toc-roc-curve-and-auc" class="nav-link" data-scroll-target="#roc-curve-and-auc"><span class="header-section-number">5.5</span> ROC Curve and AUC</a></li>
  <li><a href="#choosing-a-threshold" id="toc-choosing-a-threshold" class="nav-link" data-scroll-target="#choosing-a-threshold"><span class="header-section-number">5.6</span> Choosing a Threshold</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">6</span> Summary</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Day 8: Logistic Regression</h1>
<p class="subtitle lead">SC INBRE Biostatistics Summer Intensive 2026</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(this.path)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="fu">this.dir</span>())</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>framingham <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../../data/framingham.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">male          =</span> <span class="fu">factor</span>(male,          <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>,<span class="st">"Male"</span>)),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">currentSmoker =</span> <span class="fu">factor</span>(currentSmoker, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Non-smoker"</span>,<span class="st">"Smoker"</span>)),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">prevalentHyp  =</span> <span class="fu">factor</span>(prevalentHyp,  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>,<span class="st">"Yes"</span>)),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">diabetes      =</span> <span class="fu">factor</span>(diabetes,      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>,<span class="st">"Yes"</span>)),</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">TenYearCHD    =</span> <span class="fu">factor</span>(TenYearCHD,    <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>,<span class="st">"Yes"</span>)),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">education     =</span> <span class="fu">factor</span>(education,     <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                           <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Some HS"</span>,<span class="st">"HS Diploma"</span>,<span class="st">"Some College"</span>,<span class="st">"College Degree"</span>))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="overview" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Overview</h1>
<p>So far we have modeled continuous outcomes with linear regression. Many of the most important questions in biomedical research, however, involve <strong>binary outcomes</strong>: did the patient develop the disease, did the screening test return positive, did the treatment succeed?</p>
<p>Today we extend regression to binary outcomes using <strong>logistic regression</strong>. We will work through three examples using the Framingham Heart Study:</p>
<ul>
<li><strong>Example 1:</strong> Simple logistic regression of <code>TenYearCHD</code> on <code>sysBP</code>. Fitting, interpretation, and visualization.</li>
<li><strong>Example 2:</strong> Multiple logistic regression with several risk factors. Adjusted odds ratios, model comparison, and selection.</li>
<li><strong>Example 3:</strong> Classification performance. ROC curves, AUC, and the sensitivity/specificity tradeoff.</li>
</ul>
<hr>
</section>
<section id="why-not-linear-regression" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Why Not Linear Regression?</h1>
<p>Suppose we want to predict whether a Framingham participant will develop coronary heart disease (CHD) within 10 years, coded as 0 (no) or 1 (yes). Why can we not just run <code>lm(TenYearCHD ~ age)</code>?</p>
<p>Three problems show up immediately:</p>
<ol type="1">
<li><p><strong>The line goes outside <span class="math inline">\([0, 1]\)</span>.</strong> A straight line has no upper or lower bound. At extreme ages, linear regression will predict probabilities below 0 or above 1, which is nonsense.</p></li>
<li><p><strong>The variance is not constant.</strong> For a binary outcome, <span class="math inline">\(\text{Var}(Y) = \pi(1 - \pi)\)</span> depends on <span class="math inline">\(\pi\)</span>. Homoscedasticity (the “E” in LINE) fails by construction.</p></li>
<li><p><strong>The residuals cannot be normal.</strong> <span class="math inline">\(Y\)</span> only takes the values 0 and 1, so residuals are bimodal. The normality assumption (“N” in LINE) fails too.</p></li>
</ol>
<p>Logistic regression solves all three by modeling a <strong>transformation</strong> of the probability instead of the probability itself.</p>
<section id="the-logit-transformation" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="the-logit-transformation"><span class="header-section-number">2.1</span> The Logit Transformation</h2>
<p>Let <span class="math inline">\(\pi = P(Y = 1)\)</span>. The <strong>logit</strong> (log-odds) of <span class="math inline">\(\pi\)</span> is</p>
<p><span class="math display">\[\text{logit}(\pi) = \log\!\left(\frac{\pi}{1-\pi}\right)\]</span></p>
<p>The logistic regression model assumes the log-odds is linear in the predictors:</p>
<p><span class="math display">\[\log\!\left(\frac{\pi}{1-\pi}\right) = \beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p\]</span></p>
<p>Solving for <span class="math inline">\(\pi\)</span> gives the familiar S-shaped curve:</p>
<p><span class="math display">\[\pi = \frac{\exp(\beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p)}{1 + \exp(\beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p)}\]</span></p>
<p>This curve is bounded between 0 and 1 for any values of the predictors. Problem solved.</p>
<hr>
</section>
</section>
<section id="example-1-simple-logistic-regression-chd-on-sysbp" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Example 1: Simple Logistic Regression (CHD on sysBP)</h1>
<section id="the-question" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="the-question"><span class="header-section-number">3.1</span> The Question</h2>
<p>Does systolic blood pressure predict whether a participant develops CHD within 10 years?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>framingham <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(TenYearCHD) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="fu">round</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  TenYearCHD     n percent
  &lt;fct&gt;      &lt;int&gt;   &lt;dbl&gt;
1 No          3596    84.8
2 Yes          644    15.2</code></pre>
</div>
</div>
<p>About 15% of Framingham participants developed CHD over the follow-up. This is the <strong>baseline rate</strong>, the probability we would predict for a randomly chosen person if we had no other information.</p>
</section>
<section id="checking-variable-form" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="checking-variable-form"><span class="header-section-number">3.2</span> Checking Variable Form</h2>
<p>Before fitting, we look at how the empirical probability of CHD changes with <code>sysBP</code>. A loess smoother on the binary outcome gives a non-parametric estimate of <span class="math inline">\(\pi\)</span> as a function of <code>sysBP</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>framingham <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CHD_numeric =</span> <span class="fu">as.numeric</span>(TenYearCHD) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sysBP, <span class="at">y =</span> CHD_numeric)) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.06</span>, <span class="at">height =</span> <span class="fl">0.04</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">color =</span> <span class="st">"firebrick"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Systolic BP (mmHg)"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability of CHD within 10 years"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Empirical CHD Probability by Systolic BP"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Loess smoother on the binary outcome"</span>) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Day8_LogisticRegression_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The loess curve rises steadily with <code>sysBP</code>, suggesting that higher blood pressure is associated with higher CHD risk. The relationship looks reasonably smooth, with no sharp bends, so a single linear term on the log-odds scale is plausible.</p>
</section>
<section id="fitting-the-model" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="fitting-the-model"><span class="header-section-number">3.3</span> Fitting the Model</h2>
<p>We fit logistic regression with <code>glm()</code>. Note three changes compared to <code>lm()</code>:</p>
<ul>
<li>The function is <code>glm()</code> instead of <code>lm()</code>.</li>
<li>We specify <code>family = binomial(link = "logit")</code> (or just <code>family = binomial</code>, since logit is the default).</li>
<li>The output is on the log-odds scale.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>chd_simple <span class="ot">&lt;-</span> <span class="fu">glm</span>(TenYearCHD <span class="sc">~</span> sysBP,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> framingham,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chd_simple)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = TenYearCHD ~ sysBP, family = binomial(link = "logit"), 
    data = framingham)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -5.000050   0.255855  -19.54   &lt;2e-16 ***
sysBP        0.024057   0.001801   13.36   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3612.2  on 4239  degrees of freedom
Residual deviance: 3433.3  on 4238  degrees of freedom
AIC: 3437.3

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><strong>Reading the output:</strong></p>
<ul>
<li><strong>Intercept (<span class="math inline">\(\hat\beta_0\)</span> = -5):</strong> The log-odds of CHD when <code>sysBP = 0</code>. Not directly meaningful because nobody has zero blood pressure, but it sets the level of the line.</li>
<li><strong>sysBP (<span class="math inline">\(\hat\beta_1\)</span> = 0.0241):</strong> For each additional 1 mmHg of systolic BP, the log-odds of CHD increase by 0.0241.</li>
<li><strong>z-value and p-value:</strong> Same role as the t-test in linear regression. Strong evidence that <code>sysBP</code> is associated with CHD risk.</li>
</ul>
<p>The log-odds scale is hard to interpret. Exponentiating converts it to <strong>odds ratios</strong>, which most people find easier.</p>
</section>
<section id="odds-ratios-and-confidence-intervals" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="odds-ratios-and-confidence-intervals"><span class="header-section-number">3.4</span> Odds Ratios and Confidence Intervals</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(chd_simple), <span class="fu">confint</span>(chd_simple)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     OR       2.5 %     97.5 %
(Intercept) 0.006737607 0.004065633 0.01108845
sysBP       1.024349119 1.020751601 1.02798641</code></pre>
</div>
</div>
<p><strong>Reading the odds ratios:</strong></p>
<ul>
<li>For each additional 1 mmHg of systolic BP, the <strong>odds</strong> of CHD are multiplied by 1.024. A 1 mmHg increase is small, so the OR is close to 1.</li>
<li>The CI of (1.021, 1.028) does not include 1, so we reject the null of no association.</li>
</ul>
<p>A 1 mmHg increase is a trivial change clinically. To make this more interpretable, rescale to a <strong>20 mmHg increase</strong> (roughly one standard deviation):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">20</span> <span class="sc">*</span> <span class="fu">coef</span>(chd_simple)[<span class="st">"sysBP"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sysBP 
1.617931 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="dv">20</span> <span class="sc">*</span> <span class="fu">confint</span>(chd_simple)[<span class="st">"sysBP"</span>, ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2.5 %  97.5 % 
1.50800 1.73679 </code></pre>
</div>
</div>
<p>A 20 mmHg increase in systolic BP roughly <strong>doubles</strong> the odds of developing CHD over 10 years. That number is much more interpretable.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Always rescale the OR to a unit that means something.</strong> Reporting “OR = 1.02 per mmHg” is technically correct but conveys almost nothing. Reporting “OR = 2.05 per 20 mmHg” conveys the actual size of the effect.</p>
</div>
</div>
</section>
<section id="predicted-probabilities" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="predicted-probabilities"><span class="header-section-number">3.5</span> Predicted Probabilities</h2>
<p><code>predict()</code> returns the linear predictor (log-odds) by default. Add <code>type = "response"</code> to get probabilities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>framingham <span class="ot">&lt;-</span> framingham <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p_chd =</span> <span class="fu">predict</span>(chd_simple, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>framingham <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sysBP, TenYearCHD, p_chd) <span class="sc">|&gt;</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  sysBP TenYearCHD  p_chd
  &lt;dbl&gt; &lt;fct&gt;       &lt;dbl&gt;
1   147 Yes        0.188 
2   123 Yes        0.115 
3   125 No         0.120 
4   104 No         0.0760
5   174 No         0.307 
6   153 No         0.211 </code></pre>
</div>
</div>
<p>To predict for new individuals, build a small tibble with the relevant predictors and pass it to <code>predict()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>new_subjects <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">sysBP =</span> <span class="fu">c</span>(<span class="dv">110</span>, <span class="dv">130</span>, <span class="dv">150</span>, <span class="dv">180</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>new_subjects <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p_chd =</span> <span class="fu">predict</span>(chd_simple, <span class="at">newdata =</span> new_subjects, <span class="at">type =</span> <span class="st">"response"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  sysBP  p_chd
  &lt;dbl&gt;  &lt;dbl&gt;
1   110 0.0868
2   130 0.133 
3   150 0.199 
4   180 0.339 </code></pre>
</div>
</div>
<p>At <code>sysBP = 110</code>, the predicted CHD probability is about 8%. At <code>sysBP = 180</code>, it climbs to about 28%. A 70 mmHg increase in BP roughly triples the predicted risk.</p>
</section>
<section id="visualizing-the-fitted-curve" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="visualizing-the-fitted-curve"><span class="header-section-number">3.6</span> Visualizing the Fitted Curve</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>framingham <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CHD_numeric =</span> <span class="fu">as.numeric</span>(TenYearCHD) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sysBP, <span class="at">y =</span> CHD_numeric)) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.06</span>, <span class="at">height =</span> <span class="fl">0.04</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"glm"</span>, <span class="at">method.args =</span> <span class="fu">list</span>(<span class="at">family =</span> <span class="st">"binomial"</span>),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"firebrick"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Systolic BP (mmHg)"</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability of CHD within 10 years"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Fitted Logistic Regression Curve"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Red curve: fitted logistic model; shaded band is 95% CI for the mean"</span>) <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Day8_LogisticRegression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The fitted logistic curve rises smoothly from near 0 at low BP to about 0.4 at very high BP. The curve is bounded between 0 and 1 by construction, unlike a linear regression line.</p>
</section>
<section id="a-note-on-categorizing-continuous-predictors" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="a-note-on-categorizing-continuous-predictors"><span class="header-section-number">3.7</span> A Note on Categorizing Continuous Predictors</h2>
<p>A common modeling mistake is to chop a continuous variable like age or BP into categories before fitting. The same warning we issued for linear regression applies here:</p>
<ul>
<li>Categorization throws away information.</li>
<li>It assumes a step change at the cutpoint rather than a smooth effect.</li>
<li>It reduces statistical power.</li>
</ul>
<p>To illustrate, here is what happens if we wrongly treat <code>sysBP</code> as a factor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>framingham_bad <span class="ot">&lt;-</span> framingham <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sysBP_factor =</span> <span class="fu">cut</span>(sysBP,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">80</span>, <span class="dv">120</span>, <span class="dv">140</span>, <span class="dv">160</span>, <span class="dv">300</span>),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"&lt;120"</span>, <span class="st">"120-140"</span>, <span class="st">"140-160"</span>, <span class="st">"160+"</span>),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">include.lowest =</span> <span class="cn">TRUE</span>))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>bad_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(TenYearCHD <span class="sc">~</span> sysBP_factor,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> framingham_bad,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">family =</span> binomial)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(chd_simple, bad_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           df      AIC
chd_simple  2 3437.314
bad_model   4 3460.491</code></pre>
</div>
</div>
<p>The continuous model has a lower AIC because it captures the smooth dose-response without spending degrees of freedom on dummy variables. Keep continuous variables continuous unless there is a strong reason to categorize.</p>
<hr>
</section>
</section>
<section id="example-2-multiple-logistic-regression" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Example 2: Multiple Logistic Regression</h1>
<p>In practice we rarely have a single predictor. The real value of regression is the ability to adjust for multiple risk factors simultaneously.</p>
<section id="the-question-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="the-question-1"><span class="header-section-number">4.1</span> The Question</h2>
<p>How do age, smoking status, blood pressure, cholesterol, and diabetes jointly predict CHD risk? Which factors remain important after adjusting for the others?</p>
</section>
<section id="checking-variable-form-for-each-predictor" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="checking-variable-form-for-each-predictor"><span class="header-section-number">4.2</span> Checking Variable Form for Each Predictor</h2>
<p>Before fitting a multivariable model, inspect each continuous predictor’s relationship with the outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>framingham <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CHD_numeric =</span> <span class="fu">as.numeric</span>(TenYearCHD) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(age, sysBP, totChol, BMI),</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"predictor"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> CHD_numeric)) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>, <span class="at">height =</span> <span class="fl">0.04</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">color =</span> <span class="st">"firebrick"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> predictor, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Predictor value"</span>, <span class="at">y =</span> <span class="st">"Probability of CHD"</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Empirical CHD Probability by Each Predictor"</span>) <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Day8_LogisticRegression_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p><code>age</code> and <code>sysBP</code> show clear monotonic increases. <code>totChol</code> shows a weaker positive trend. <code>BMI</code> rises and then flattens (worth keeping in mind, but not strong enough to require a spline for this example).</p>
</section>
<section id="fitting-the-full-model" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="fitting-the-full-model"><span class="header-section-number">4.3</span> Fitting the Full Model</h2>
<p>We are going to restrict to complete cases on all the variables we plan to use before fitting anything. This way the data will have the same observations for all models.</p>
<p>For example, there are some missing <code>BMI</code> values. If we don’t do this step and we were to remove <code>BMI</code> from the predictor list, then we would have a different dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>vars_used <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"TenYearCHD"</span>, <span class="st">"age"</span>, <span class="st">"currentSmoker"</span>, <span class="st">"sysBP"</span>,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"totChol"</span>, <span class="st">"diabetes"</span>, <span class="st">"BMI"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>framingham_cc <span class="ot">&lt;-</span> framingham <span class="sc">|&gt;</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(<span class="fu">all_of</span>(vars_used))</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(framingham) <span class="sc">-</span> <span class="fu">nrow</span>(framingham_cc)  <span class="co"># how many rows were dropped</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 68</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>chd_full <span class="ot">&lt;-</span> <span class="fu">glm</span>(TenYearCHD <span class="sc">~</span> age <span class="sc">+</span> currentSmoker <span class="sc">+</span> sysBP <span class="sc">+</span> totChol <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                              diabetes <span class="sc">+</span> BMI,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> framingham_cc,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> binomial)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chd_full)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = TenYearCHD ~ age + currentSmoker + sysBP + totChol + 
    diabetes + BMI, family = binomial, data = framingham_cc)

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -8.216150   0.476457 -17.244  &lt; 2e-16 ***
age                  0.065593   0.006055  10.834  &lt; 2e-16 ***
currentSmokerSmoker  0.554136   0.095849   5.781 7.41e-09 ***
sysBP                0.015600   0.002086   7.478 7.55e-14 ***
totChol              0.001228   0.001016   1.208  0.22714    
diabetesYes          0.727067   0.221828   3.278  0.00105 ** 
BMI                  0.014302   0.011255   1.271  0.20380    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3524.3  on 4171  degrees of freedom
Residual deviance: 3193.2  on 4165  degrees of freedom
AIC: 3207.2

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</section>
<section id="adjusted-odds-ratios" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="adjusted-odds-ratios"><span class="header-section-number">4.4</span> Adjusted Odds Ratios</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(chd_full), <span class="fu">confint</span>(chd_full))) <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       OR 2.5 % 97.5 %
(Intercept)         0.000 0.000  0.001
age                 1.068 1.055  1.081
currentSmokerSmoker 1.740 1.443  2.102
sysBP               1.016 1.012  1.020
totChol             1.001 0.999  1.003
diabetesYes         2.069 1.328  3.176
BMI                 1.014 0.992  1.037</code></pre>
</div>
</div>
<p><strong>Interpretation of each coefficient:</strong></p>
<ul>
<li><strong>age:</strong> Each additional year of age multiplies the odds of CHD by about 1.06, holding the other variables constant. Over a decade, that’s <span class="math inline">\(1.06^{10} \approx 1.8\)</span>, so the odds roughly double.</li>
<li><strong>currentSmokerSmoker:</strong> Smokers have about 50% higher odds of CHD than non-smokers of the same age, BP, cholesterol, BMI, and diabetes status. This is the “Smoker vs Non-smoker” contrast, with non-smokers as the reference.</li>
<li><strong>sysBP:</strong> Per 1 mmHg, the OR is just above 1. The 20-mmHg-scaled OR is 1.37.</li>
<li><strong>totChol:</strong> Per mg/dL, the OR is essentially 1. Scaled to a 40 mg/dL change, the OR becomes 1.05.</li>
<li><strong>diabetesYes:</strong> Diabetic participants have substantially higher CHD odds even after adjusting for the other risk factors.</li>
<li><strong>BMI:</strong> The CI typically includes 1 in this dataset, meaning BMI does not add much once the other variables are accounted for.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The coefficient for sysBP in the multiple model is <strong>smaller</strong> than in the simple model from Example 1. This is because part of the sysBP effect we saw earlier was actually attributable to age (older participants tend to have higher BP and more CHD). Once we adjust for age, the unique contribution of sysBP is smaller. This is the entire point of multivariable regression.</p>
</div>
</div>
</section>
<section id="comparing-nested-models-likelihood-ratio-test" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="comparing-nested-models-likelihood-ratio-test"><span class="header-section-number">4.5</span> Comparing Nested Models: Likelihood Ratio Test</h2>
<p>To test whether a group of predictors adds anything jointly, use the <strong>likelihood ratio test (LRT)</strong>, the logistic-regression analog of the partial F-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reduced model: drop diabetes and BMI</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>chd_reduced <span class="ot">&lt;-</span> <span class="fu">glm</span>(TenYearCHD <span class="sc">~</span> age <span class="sc">+</span> currentSmoker <span class="sc">+</span> sysBP <span class="sc">+</span> totChol,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> framingham_cc,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">family =</span> binomial)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(chd_reduced, chd_full, <span class="at">test =</span> <span class="st">"LRT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: TenYearCHD ~ age + currentSmoker + sysBP + totChol
Model 2: TenYearCHD ~ age + currentSmoker + sysBP + totChol + diabetes + 
    BMI
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)   
1      4167     3205.5                        
2      4165     3193.2  2    12.29 0.002144 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The LRT compares the deviances of the two models. A small p-value means the dropped variables (diabetes and BMI) collectively add useful information. A large p-value would suggest we can simplify.</p>
<p>Use <code>anova(reduced, full, test = "LRT")</code> whenever you want to test:</p>
<ul>
<li>A multi-level categorical predictor (all its dummy variables jointly).</li>
<li>A polynomial or spline expansion of a variable.</li>
<li>A group of related predictors entering or leaving together.</li>
</ul>
</section>
<section id="model-selection-with-aic" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="model-selection-with-aic"><span class="header-section-number">4.6</span> Model Selection with AIC</h2>
<p>For exploratory model building, AIC-based stepwise selection often works well as a starting point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>chd_step <span class="ot">&lt;-</span> <span class="fu">step</span>(chd_full, <span class="at">direction =</span> <span class="st">"both"</span>, <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(chd_step)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = TenYearCHD ~ age + currentSmoker + sysBP + diabetes, 
    family = binomial, data = framingham_cc)

Coefficients:
                     Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -7.706964   0.372289 -20.702  &lt; 2e-16 ***
age                  0.066225   0.005990  11.056  &lt; 2e-16 ***
currentSmokerSmoker  0.535994   0.094861   5.650  1.6e-08 ***
sysBP                0.016600   0.001991   8.335  &lt; 2e-16 ***
diabetesYes          0.750648   0.221032   3.396 0.000684 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 3524.3  on 4171  degrees of freedom
Residual deviance: 3196.3  on 4167  degrees of freedom
AIC: 3206.3

Number of Fisher Scoring iterations: 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(chd_full, chd_step)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         df      AIC
chd_full  7 3207.249
chd_step  5 3206.321</code></pre>
</div>
</div>
<p>The stepwise procedure typically drops <code>BMI</code> from this model. The selected model has a slightly lower AIC than the full model, suggesting a small improvement after removing the weakest predictor.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>A warning about stepwise selection.</strong> AIC-based stepwise procedures are a reasonable exploratory tool but are known to over-fit and produce overly confident p-values on the selected variables. For inference about a specific scientific question, decide on your model based on subject-matter knowledge, not on stepwise output. For prediction, methods like LASSO (Day 14) are usually preferable.</p>
</div>
</div>
</section>
<section id="final-model-and-its-odds-ratios" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="final-model-and-its-odds-ratios"><span class="header-section-number">4.7</span> Final Model and Its Odds Ratios</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>chd_final <span class="ot">&lt;-</span> chd_step</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(chd_final), <span class="fu">confint</span>(chd_final))) <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       OR 2.5 % 97.5 %
(Intercept)         0.000 0.000  0.001
age                 1.068 1.056  1.081
currentSmokerSmoker 1.709 1.420  2.060
sysBP               1.017 1.013  1.021
diabetesYes         2.118 1.362  3.246</code></pre>
</div>
</div>
<p>This is the table you would report in a paper, after rescaling continuous predictors to clinically meaningful units.</p>
<hr>
</section>
</section>
<section id="example-3-classification-and-predictive-performance" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Example 3: Classification and Predictive Performance</h1>
<p>Logistic regression gives a predicted probability <span class="math inline">\(\hat\pi_i\)</span> for each subject. To turn this into a yes/no classification, we pick a <strong>threshold</strong> <span class="math inline">\(\pi_0\)</span> and classify:</p>
<p><span class="math display">\[\hat Y_i = \begin{cases} 1 &amp; \text{if } \hat\pi_i &gt; \pi_0 \\ 0 &amp; \text{if } \hat\pi_i \le \pi_0 \end{cases}\]</span></p>
<p>The threshold is a choice, not a property of the model. Different thresholds produce different tradeoffs between sensitivity and specificity.</p>
<section id="generating-predicted-probabilities" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="generating-predicted-probabilities"><span class="header-section-number">5.1</span> Generating Predicted Probabilities</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>framingham_cc <span class="ot">&lt;-</span> framingham_cc <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p_chd_final =</span> <span class="fu">predict</span>(chd_final, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>framingham_cc <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(TenYearCHD, p_chd_final) <span class="sc">|&gt;</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> TenYearCHD  p_chd_final     
 No :3547   Min.   :0.02162  
 Yes: 625   1st Qu.:0.07270  
            Median :0.11854  
            Mean   :0.14981  
            3rd Qu.:0.19485  
            Max.   :0.80664  </code></pre>
</div>
</div>
<p>The predicted probabilities range from very low (about 1%) to relatively high (about 65%). Most people are below 0.5, which makes sense: only 15% of the cohort actually develops CHD.</p>
</section>
<section id="confusion-matrix-at-threshold-0.5" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="confusion-matrix-at-threshold-0.5"><span class="header-section-number">5.2</span> Confusion Matrix at Threshold = 0.5</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>threshold_05 <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>framingham_cc <span class="ot">&lt;-</span> framingham_cc <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred_class_05 =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(p_chd_final <span class="sc">&gt;</span> threshold_05, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> framingham_cc<span class="sc">$</span>pred_class_05, <span class="at">Actual =</span> framingham_cc<span class="sc">$</span>TenYearCHD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   No  Yes
      No  3520  597
      Yes   27   28</code></pre>
</div>
</div>
<p>At a threshold of 0.5, almost no one gets classified as a predicted CHD case. The model is right about most non-cases but misses almost all the actual cases. A 0.5 threshold is rarely a good default when the event is rare.</p>
</section>
<section id="confusion-matrix-at-threshold-0.15-the-event-rate" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="confusion-matrix-at-threshold-0.15-the-event-rate"><span class="header-section-number">5.3</span> Confusion Matrix at Threshold = 0.15 (the Event Rate)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>threshold_15 <span class="ot">&lt;-</span> <span class="fl">0.15</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>framingham_cc <span class="ot">&lt;-</span> framingham_cc <span class="sc">|&gt;</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred_class_15 =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(p_chd_final <span class="sc">&gt;</span> threshold_15, <span class="st">"Yes"</span>, <span class="st">"No"</span>),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)))</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">Predicted =</span> framingham_cc<span class="sc">$</span>pred_class_15, <span class="at">Actual =</span> framingham_cc<span class="sc">$</span>TenYearCHD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   No  Yes
      No  2398  213
      Yes 1149  412</code></pre>
</div>
</div>
<p>Lowering the threshold to 0.15 means we now flag many more people as predicted CHD cases. Sensitivity goes up; specificity goes down. The right tradeoff depends on the relative cost of missing a true case versus a false alarm.</p>
</section>
<section id="sensitivity-specificity-ppv-npv" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sensitivity-specificity-ppv-npv"><span class="header-section-number">5.4</span> Sensitivity, Specificity, PPV, NPV</h2>
<p>For a given confusion matrix, four summary numbers describe performance:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> framingham_cc<span class="sc">$</span>pred_class_15, <span class="at">Actual =</span> framingham_cc<span class="sc">$</span>TenYearCHD)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   No  Yes
      No  2398  213
      Yes 1149  412</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>TP <span class="ot">&lt;-</span> tab[<span class="st">"Yes"</span>, <span class="st">"Yes"</span>]</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>FP <span class="ot">&lt;-</span> tab[<span class="st">"Yes"</span>, <span class="st">"No"</span>]</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>TN <span class="ot">&lt;-</span> tab[<span class="st">"No"</span>,  <span class="st">"No"</span>]</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>FN <span class="ot">&lt;-</span> tab[<span class="st">"No"</span>,  <span class="st">"Yes"</span>]</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sensitivity =</span> TP <span class="sc">/</span> (TP <span class="sc">+</span> FN),  <span class="co"># of actual CHD cases, fraction we caught</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Specificity =</span> TN <span class="sc">/</span> (TN <span class="sc">+</span> FP),  <span class="co"># of actual non-cases, fraction we cleared</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">PPV         =</span> TP <span class="sc">/</span> (TP <span class="sc">+</span> FP),  <span class="co"># of flagged cases, fraction that are true</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">NPV         =</span> TN <span class="sc">/</span> (TN <span class="sc">+</span> FN)   <span class="co"># of cleared cases, fraction that are true</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  Sensitivity Specificity   PPV   NPV
        &lt;dbl&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1       0.659       0.676 0.264 0.918</code></pre>
</div>
</div>
</section>
<section id="roc-curve-and-auc" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="roc-curve-and-auc"><span class="header-section-number">5.5</span> ROC Curve and AUC</h2>
<p>The <strong>ROC curve</strong> plots sensitivity against (1 - specificity) for every possible threshold. It summarizes the full sensitivity-specificity tradeoff in one picture.</p>
<p>The <strong>AUC</strong> (area under the ROC curve) is a single-number summary. It can be interpreted as the probability that the model assigns a higher predicted probability to a randomly chosen CHD case than to a randomly chosen non-case.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>roc_obj <span class="ot">&lt;-</span> <span class="fu">roc</span>(framingham_cc<span class="sc">$</span>TenYearCHD, framingham_cc<span class="sc">$</span>p_chd_final,</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>), <span class="at">direction =</span> <span class="st">"&lt;"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_obj, <span class="at">col =</span> <span class="st">"firebrick"</span>, <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"ROC Curve for CHD Prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Day8_LogisticRegression_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">auc</span>(roc_obj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve: 0.7211</code></pre>
</div>
</div>
<p>The AUC for this model is around 0.72, which is in the “acceptable” range for clinical risk prediction. Models with AUC below 0.6 rarely provide clinical value; models above 0.8 are excellent for many applications.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>AUC</th>
<th>Discriminative ability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\approx\)</span> 0.5</td>
<td>No discrimination (coin flip)</td>
</tr>
<tr class="even">
<td>0.6 – 0.7</td>
<td>Poor</td>
</tr>
<tr class="odd">
<td>0.7 – 0.8</td>
<td>Acceptable</td>
</tr>
<tr class="even">
<td>0.8 – 0.9</td>
<td>Excellent</td>
</tr>
<tr class="odd">
<td>&gt; 0.9</td>
<td>Outstanding</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>A caution on AUC values reported from the training data.</strong> The AUC we just computed was evaluated on the same data used to fit the model. This is <strong>optimistic</strong>: it overestimates how well the model will perform on new data. For an honest assessment, evaluate on held-out data or use cross-validation (Day 7).</p>
</div>
</div>
</section>
<section id="choosing-a-threshold" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="choosing-a-threshold"><span class="header-section-number">5.6</span> Choosing a Threshold</h2>
<p>The threshold is a clinical decision, not a statistical one. It depends on the cost of false positives versus false negatives.</p>
<ul>
<li><strong>For CHD screening:</strong> Missing a true case (false negative) means a patient doesn’t get preventive treatment for a serious condition. False positives mean unnecessary follow-up. Most screening programs accept many false positives to catch as many true cases as possible, so the threshold is set low (high sensitivity).</li>
<li><strong>For a one-time, costly intervention:</strong> The threshold is set higher so that only people very likely to benefit are treated.</li>
</ul>
<p>You can use the ROC object to find the threshold that maximizes some criterion of interest:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Youden's J statistic: maximize sensitivity + specificity - 1</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coords</span>(roc_obj, <span class="st">"best"</span>, <span class="at">best.method =</span> <span class="st">"youden"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  threshold specificity sensitivity
1 0.1398789   0.6425148      0.6976</code></pre>
</div>
</div>
<p>This returns the threshold that achieves the best balance of sensitivity and specificity by Youden’s J criterion. The clinician’s job is to decide whether that balance is the right one for the application.</p>
<hr>
</section>
</section>
<section id="summary" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Summary</h1>
<p>Logistic regression extends the regression framework to binary outcomes. The model has the same shape as linear regression but on the log-odds scale.</p>
<p>Three key skills from this lecture:</p>
<ol type="1">
<li><p><strong>Fit and interpret.</strong> Use <code>glm()</code> with <code>family = binomial</code>. Report exponentiated coefficients (odds ratios), rescaled to clinically meaningful units, with confidence intervals.</p></li>
<li><p><strong>Compare and select models.</strong> Use <code>anova(reduced, full, test = "LRT")</code> for nested model tests. Use <code>AIC()</code> or <code>step()</code> for exploratory selection, but recognize their limitations.</p></li>
<li><p><strong>Evaluate predictive performance.</strong> Predicted probabilities turn into classifications via a threshold. ROC curves and AUC summarize the full tradeoff. The choice of threshold is application-specific.</p></li>
</ol>
<p>Tomorrow we extend regression in a different direction: instead of binary outcomes, we will look at <strong>time-to-event</strong> outcomes (survival analysis), where we track not just whether the event happened but when.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="Day8_LogisticRegression_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>